### ISSUE TITLE
Migrate from gocode to golsp

### ISSUE THREAD

**Issue by creasty** [creasty/dotfiles#52]
https://mattn.kaoriya.net/software/lang/go/20181217000056.htm

**Comment by creasty** [comment]
Useless piece of shit.

```
月  2/11 16:36:32 2019:["<---(stderr)",1,"gopls",["panic: runtime error: invalid memory address or nil pointer dereference","[signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0x128b86e]","","goroutine 23 [running]:","golang.org/x/tools/go/analysis/passes/atomicalign.run(0xc005353560, 0xc006397ff0, 0x1716f80, 0xc004e91e58, 0x0)","\t/Users/ykiwng/go/src/golang.org/x/tools/go/analysis/passes/atomicalign/atomicalign.go:30 +0x2e",""]]
月  2/11 16:36:32 2019:["<---(stderr)",1,"gopls",["golang.org/x/tools/internal/lsp/source.runAnalyses.func2.1()","\t/Users/ykiwng/go/src/golang.org/x/tools/internal/lsp/source/diagnostics.go:285 +0x532","sync.(*Once).Do(0xc003f9ef00, 0xc000047f68)","\t/usr/local/Cellar/go/1.11/libexec/src/sync/once.go:44 +0xb3","golang.org/x/tools/internal/lsp/source.runAnalyses.func2(0x1716960, 0x0)","\t/Users/ykiwng/go/src/golang.org/x/tools/internal/lsp/source/diagnostics.go:246 +0xd2","golang.org/x/tools/internal/lsp/source.runAnalyses.func3.1(0xc007fd1b50, 0xc0083167a0, 0x1716960)","\t/Users/ykiwng/go/src/golang.org/x/tools/internal/lsp/source/diagnostics.go:294 +0x33","created by golang.org/x/tools/internal/lsp/source.runAnalyses.func3","\t/Users/ykiwng/go/src/golang.org/x/tools/internal/lsp/source/diagnostics.go:293 +0xa3",""]]
月  2/11 16:36:32 2019:["s:on_exit",1,"gopls","exited",2]
```
